### ISSUE TITLE
[Bug]: Pause and Next Frame keyboard shortcuts don't work

### ISSUE THREAD

**Issue by YourBuddyBill** [visualboyadvance-m/visualboyadvance-m#1077]
### Expected behavior?

Pressing Ctrl+P while emulation is running should pause the emulation. Pressing Ctrl+N while paused should advance emulation by one frame.

### Actual behavior?

Pressing Ctrl+P does nothing. After pausing manually via the menu, pressing Ctrl+N while paused unpauses emulation except the menu still has Pause checked and thinks it's still paused.

Trying to do more Ctrl+N afterwards and more Ctrl+P sometimes actually makes the shortcuts do what you'd expect them to, but not always.

### Steps to reproduce the problem

1. Go into any game (only tested with Shantae as it seems to be a UI bug)
2. Press Ctrl+P
3. Observe
4. Go to the menu bar and Pause emulation from there
5. Press Ctrl+N
6. Observe
7. Press Ctrl+N again and it might advance one frame
8. Try to use the menu to unpause, fail.
9. Press Ctrl+N or Ctrl+P more to make it sometimes work and sometimes not, I haven't figured out the logic behind the behavior, sorry.

### Error messages?

None

### What game were you playing

Title: Shantae
GB, GBC or GBA: GBC
ROM CODE: No idea.
BIOS Used?: No idea.
SAVE TYPE: Battery, but also using savestates.
Clean, Intro'd or Hacked?: Pretty sure it's clean?
Screenshot attached.
![shantae rom settings](https://user-images.githubusercontent.com/4391382/218290437-acae7706-7572-4149-b17b-1d78a494e83e.png)

### What settings are you using?

Video driver (simple, opengl): OpenGL but it applies to Simple too
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: At 3x scale, but no "Display Filter"

### Specifications and Build details

VBA-M: Nightly 64 bit 2.1.5-4b605b4b, problem applied in 2.1.5 available from the releases page too though.
OS: Windows 10 Version 22H2 OS Build 19045.2364

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
PAUSE binding works, so this must be at the keyboard handling level.

**Comment by PrimaIVoid** [comment]
I think the inputs taken from keyboard doesn't always work if the emulator window goes "out of focus" and that happens often in my case when playing in windowed mode. To make it work again (for example the Pause/Unpause througth Ctrl+P) you just need to mouse over the top menu and click anythink, after doing that, it will regain focus on the window and Ctrl + P should work again
I'm not sure which is the cause that make the window lose focus though since even without moving the mouse outside of the window and even without Alt/Tab it frequently lost focus if you try any key combination related to the emulator keybinding
(Example: Save state - Load state)

**Comment by Squall-Leonhart** [comment]
Nothing to do with window focus, the pause button works, but letters, numbers and combo's including them don't

**Comment by PrimaIVoid** [comment]
They do work if the window is on focus, but when this strange "bug/behaviour" occur and the window goes out of focus, only then they stop to work. Now i'm calling this "goes out of focus" because i don't know which term to use, but its not exactly like that

I can still play any rom while the window is "in focus" and use any keybind (letters, numbers ...) without problems, but as soon as it somehow lost focus, then the keybinds stop to work/be responsive BUT i can still play the rom normally without problems. It's a bit confusing to explain i admit

**Comment by rkitover** [comment]
This may be related to the background input support, if you say the window somehow loses focus.

Do you know how the window loses focus? Does it happen in fullscreen mode?

**Comment by Squall-Leonhart** [comment]
Its not related to window focus at all,  Pause|Break is working reliably where CTRL+P can only unpause.
