### ISSUE TITLE
[Bug]: Frame Pacing/Frame rate/Stuttering issue

### ISSUE THREAD

**Issue by sappergr** [visualboyadvance-m/visualboyadvance-m#1180]
### Expected behavior?

Smooth Frame Rate

### Actual behavior?

Stuttering, fps choppiness with both OpenGL and Simple Rendering, Nvidia Graphics. Somewhat better with vsync on but still far from perfect.

### Steps to reproduce the problem

just try a game

### What settings are you using?

Video driver (simple, opengl): Both
Sound driver (directsound, xaudio, openal, SDL): Any
Scale Filter Used?: None

### Specifications and Build details

VBA-M: Latest Release 2.1.6
OS: Windows and Linux, The issue persists in both
If using Linux, specify if using xorg or Wayland:xorg
CPU: FX4300
GPU: GT730
RAM: 8gigs

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Your cpu is throttling either due to a configuration issue or simply not being loaded high enough, you would best consult a tech forum where users knowledgeable about the inherent behaviors of a Bulldozer CPU are.

These cpu's are known to be misconfigured at most motherboard optimal defaults with the HTT not configured correctly, as well as.

There are other potential causes such as platform dpc issues or interrupt storms, but this is not a support forum for unique issues specific to systems.

**Comment by rkitover** [comment]
You can try skipping a few frames to see if it smooths out the choppiness.

Under `Options -> Video -> Configure -> Speed` try setting a few frames to skip.

Good luck!

**Comment by sappergr** [comment]
I would agree this is a hardware/throttling/etc issue if it didn't  happen only with vba-m
