### ISSUE TITLE
Directory settings aren't saved

### ISSUE THREAD

**Issue by andoruB** [visualboyadvance-m/visualboyadvance-m#153]
OS: Debian Sid amd64
Version: commit 1fc0966

Whenever I set directories for ROMs or battery saves (Options -> Directories), and then proceed to close the emulator and then reopen it, the fields where the paths were previously set are empty.  
Looking into ~/.vbam/vbam.conf, the paths are correctly set in their respective setting entries, but when browsing for ROMs, the emulator only drops me to the last used directory, and when opening one ROM, the battery isn't loaded, instead it gets created in the same folder as the ROMs.

**Comment by acepow3r** [comment]
Confirmed...
OS: Windows 8.1 64bit

**Comment by josuegaleas** [comment]
Same issue here. It also affects the location of the BIOS file, but the path is set in `vbam.ini`.

OS: macOS 10.12.6
Version: 2.0.1-d7ff2afb

**Comment by LuismaSP89** [comment]
Same here, confirmed in windows 10 x64. 
Vba-m 2.0.1

**Comment by RinMaru** [comment]
yep confirmed Win10 x64 
VBAM 2.0.1

**Comment by MelchiorGaspar** [comment]
Me too.. meh >_>
OS: Windows 7 ULTIMATE SP1 64bit
vba-m  (v2.0.1)

**Comment by slacknk** [comment]
Me too: 2.0.1-afb1cd3d (Linux)

**Comment by Burningocean2012** [comment]
I also have this problem!Every time I play a game I have to reset directories and its annoying.I really do like this project alot and this is my only complaint.

OS: Windows 8.1 x64bit
vba-m (v2.0.1)

**Comment by frozenMustelid** [comment]
Confirmed. Directories fields in options are blank every time I open the program. If I set them, close the options window, and open the options window again, they're there, but if I close the program and reopen they're gone.

OS: Linux Mint 18.2
2.0.1 (downloaded and built archive a week or two ago).

**Comment by rkitover** [comment]
Will definitely try to fix for next release.

**Comment by cooperate** [comment]
I am trying to resolve it myself though because I don't really want to wait for the next push.

PERTAINING TO GBA BIOS

Unfortunately I am not familiar with wxWidgets nor this codebase but I am syphoning through it to try and find the solution.

Can a developer confirm if this is where the code is being handled to load the configuration settings?

CPUInit(gopts.gba_bios.mb_fn_str(), useBiosFileGBA); It is defined @ panel.cpp line 285

CPUInit is also called like this
CPUInit(biosFileNameGBA, useBios); @ SDL.cpp line 1825

This function loads in the bios file name. It is defined @ GBA.cpp line 3298

The bios file name grabs the value from the config from function LoadConfig @ ConfigManager.cpp line 464
with this:
biosFileNameGBA = ReadPrefString("biosFileGBA");

LoadConfig() is called @ SDL.cpp on line 1718

with this comment:
LoadConfig(); // Parse command line arguments (overrides ini)

so according to this LoadConfig is only used to override the ini setting when vba-m has additional command line arguments. 

So we need to find where the config settings are initially loaded from when the application is launched...
which seem to be using this object gopts...which as far as i can tell is defined in opts.cpp line 38...
opts_t gopts;
opts_t also defines some ui component
wxString gba_bios
this array opt_desc opt
contains
STROPT("GBA/BiosFile", "", wxTRANSLATE("BIOS file to use, if enabled"), gopts.gba_bios),

This defines a section and the corresponding ini setting to search for. Then I think it's taking that value and setting it to the object string gopts.gba_bios.
if i try to force "BiosFile" in the GBA section of the ini though it doesn't do anything. In fact after I load an instance of vba-m and exit it deletes the line with "BiosFile".

There is a line that says "biosFileGBA" in the ini however. If I change the above line to
STROPT("GBA/biosFileGBA", "", wxTRANSLATE("BIOS file to use, if enabled"), gopts.gba_bios)
this doesn't fix anything.

So the problem stems deeper into how vba-m is actually reading and writing to the ini/cfg file.

This function:
void OpenPreferences(const char *name)
{
if (!preferences && name)
preferences = iniparser_load(name);
}

is actually reading from the config.ini file

it calls a function iniparser_load which returns a dictionary. it has this description
This is the parser for ini files. This function is called, providing
the name of the file to be read. It returns a dictionary object that
should not be accessed directly, but through accessor functions
instead.

So now I'm at a wall because I don't have VS2013 I can't properly build the project to actually debug this and see what iniparser_load is returning

**Comment by nhdailey** [comment]
The Options -> Directories issue was affecting me too... using git bisect, it started here:

https://github.com/visualboyadvance-m/visualboyadvance-m/commit/0bdbcf318833daa03654e7926cf702e48b9bc418

I was able to fix by making the following change:

--- a/src/wx/opts.cpp
+++ b/src/wx/opts.cpp
@@ -479,6 +479,7 @@ void load_opts()
         opt_desc& opt = opts[i];
 
         if (opt.stropt) {
+            cfg->Read(opt.opt, opt.stropt, *opt.stropt);
             opt.curstr = *opt.stropt;
         } else if (!opt.enumvals.empty()) {
             auto enum_opts = str_split(opt.enumvals.MakeLower(), wxT("|"));

**Comment by ZachBacon** [comment]
just going to reopen this until this is properly resolved.

**Comment by wfowler1** [comment]
Oh, RIP. I made issue #196, probably the same thing.
