### ISSUE TITLE
Store "vbam.ini" in the same folder as "VisualBoyAdvance-M.exe"

### ISSUE THREAD

**Issue by LuismaSP89** [visualboyadvance-m/visualboyadvance-m#155]
I´ve been using the visualboyadvance-m (git) for a long time, i updated now to the 2.0.1 version, and now the "vbam.ini" is stored at appdata\local.

The thing is... why this change? storing the .ini in the same folder, you got a portable vba-m and you can put it in a usb stick to play anywhere. And i have .bat executables to copy different configs depending on game. With this new path, i can´t use them between different computers :S

**Comment by rkitover** [comment]
As far as I know nothing was changed affecting this code, the `appdata` path is the default, but I believe if you put the `vbam.ini` in the same folder as the `.exe` it will find it there instead.

**Comment by MelchiorGaspar** [comment]
that and the directory struectre in the Win32 bin archive needs reworking...
its currently setup  like a compiler output structure, but it needs to be in the format that it will actually run with.. exe/ini in root, sub-dir for ROMS, SaveState, SRAM, etc

unless you guys changed it around.. O_o ???

**Comment by rkitover** [comment]
Yeah I think at some point we'll make separate installer and "portable" versions, with the "portable" version laid out like you describe.

**Comment by MelchiorGaspar** [comment]
ok good.. 
well that explains why the archive was laid out unusually.. 
lol :P

**Comment by ZachBacon** [comment]
it's based on unix FHS. I was basically lazy and just archived it all.

**Comment by MelchiorGaspar** [comment]
lol... :P  ;) 
Please.. fix for the next release >_> ;) lol
plus there was that issue with vba-m not saving the directory settings.. on exit...
but there was a another ticket for that .. ;)

**Comment by ZachBacon** [comment]
Within due time we will resolve issues, some of us like myself have a full time job that takes priority. I do this on my spare time for nothing because I love the project and this was more of a get it out the door fast that it was so hot out of the oven. But yeah as @rkitover  mentioned, there's going to be an installer available soon too.

**Comment by MelchiorGaspar** [comment]
ik ik we all have lives.. ;)   ;^_^;  
thx for all you do you made it possible to play games otherwise too annoying 
to deal with with those super TINY screens lol =/  .. meh.. ;) 

lol as long as you keep the archive format too.. 
As an advanced PS user I know how to manually install for many programs that come as archived FREEware  lol ;)  and for emu I don't like installers..


btw I see two exes 
vbam.exe  <-- smaller and doesn't appear to do anything. whats this one about? O_o
VisualBoyAdvance-M.exe <<-- main

**Comment by ZachBacon** [comment]
vbam.exe is the command line SDL2 binary, basically no Gui etc for those that like something minimalistic

**Comment by MelchiorGaspar** [comment]
ooh... a popup for cmds might be helpful or a wiki or toss it all in a txt file included with the program.. O_o
basic help cmd..
M$  uses  = [ /? ]
many open src use = -h -help --h -- help
lol ;) just a thought ;)

**Comment by ZachBacon** [comment]
Well it's meant to be run from CMD.exe or by dragging a ROM to the executable. :P

**Comment by MelchiorGaspar** [comment]
ooh ok lol nvm.. I will never use that then.. 
so ....
I WILL PURGE it with HOLY VENGEANCE lol ;) ;P  
mwhahaha lol..

**Comment by Zerowalker** [comment]
I second this, love when you got the portable mode so to speak.
Many emulators use a trick, so if you create a file "portable.txt",
the game will go into Portable mode instead of storing stuff in the User folders.

**Comment by ZachBacon** [comment]
Again, already has a portable mode, you need the settings file beside it, even if it means creating a blank one before first run.

**Comment by LeyendaV** [comment]
9 years and this keeps happening. Stuff moves to AppData by itself if you update.
