### ISSUE TITLE
Different Save Types in Different Versions of the Same Region of the GBA Game?

### ISSUE THREAD

**Issue by P0W3** [visualboyadvance-m/visualboyadvance-m#156]
I have two GBA games that have the different save types.

Super Mario Bros. (J) (Hot Mario Campaign)

`saveType=0`

Famicom Mini - Vol 1 - Super Mario Bros. (J)

`saveType=1`

I have vba-over.ini, which I already chose saveType=1.

How can I play both of these GBA games that have the different save types, while I am using vba-over.ini?

[vba-over.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/1403837/vba-over.zip)

**Comment by ZachBacon** [comment]
Technically you don't need vba-over with the main vba-m program. During compilation it makes use of bin2c and basically turns vba-over into a c string which then gets compiled into the program to use internally. Chances are despite that, because there was a different change to automatically detect save types that it's causing conflict and overriding vba-over, both the internal copy and external copy. I'll investigate when I have more time

**Comment by Squall-Leonhart** [comment]
This should be handled in the save detect system now.
