### ISSUE TITLE
Full screen f11 does not work after rom loading

### ISSUE THREAD

**Issue by wingedonezero** [visualboyadvance-m/visualboyadvance-m#158]
### Expected behavior

F11 going full screen

### Actual behavior 

Nothing only goes full screen with no rom loaded

### Steps to reproduce the behavior

Hit f11 with rom loaded and without

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

All games gb, gbc and gba

### Option details

Video driver (simple, opengl):

Simple and opengl same

Operating System (Windows, Mac, Linux (state distribution), etc.):

Windows 10

Program version 2.0.1

**Comment by RhinoKneel** [comment]
I've actually found this to be with all keyboard shortcuts after loading. Can't reset, save state, quick switch game, nothing.

**Comment by wingedonezero** [comment]
Yea seems to be the case i didn't try any of the others but i have found that a older version i had that was beta 4 works fine. So it had to be something that changed between then and this release.

**Comment by BanCrash** [comment]
I'd have the same issue. I found out that, for default, the key for screenshot and for full screen it's the same (F11). I change on Options -> Input -> Configure -> Special, the key for screenshots from F11 to F12. Now it seems to work properly.

**Comment by BanCrash** [comment]
Well, if I launch the game from an external application (Launchbox) seems to not work neither.

**Comment by wingedonezero** [comment]
I can confirm what you mentioned clearing all inputs resetting the keys and adding f12 to the screenshot section fixes this issue. It must be a problem with mixed up hot key defaults then with full screen and screenshot.

**Comment by rkitover** [comment]
I had a few weeks ago removed the `F11` mapping for "save state".

Currently, as far as I can tell, the only thing `F11` is mapped to by default is "full screen" on Windows and Linux.

What is probably happening here, is that you guys have your old configs from some time when this mapping existed and it got saved into the config.

I verified that `F11` invokes entry into full screen on a fresh Windows build with no config.

**Comment by BanCrash** [comment]
I try with a fresh installation and can confirm what you said. I never mapped a key for screenshot, that's why I thought this would be a problem with the build.

Btw, sorry for open a duplicate issue, I don't know why I thought I searched for that issue too yesterday when I was searching for this issue. My bad.

**Comment by rkitover** [comment]
Well, how would you suggest we fix this, I was thinking I could check if any configured keymappings conflict with app keymappings and remove them or something.

**Comment by BanCrash** [comment]
That sounds pretty well to me. 
But if that is going to be a hard job of codding maybe could be useful release a hotfix that resets the default keymappings on every version update until that job is done, to workaround this issue at the moment. This assuming this would be more fast and easy than the other thing, obviously.

**Comment by Nicholas-Steel** [comment]
Unsure if this is related or not, but when a ROM is loaded the Alt-F4 keyboard shortcut is ignored by the program. So when I encountered the inability to leave Fullscreen (I was entering Fullscreen via the Menu Bar) I had to Alt-Tab or Ctrl-Alt-Delete to access a method of closing the program.

**Comment by ZachBacon** [comment]
In your case, have you hit the escape key? Just curious.

**Comment by Nicholas-Steel** [comment]
Okay, so the first few attempts at using v2.01 I would load the emulator, load a game and use the Menu Bar to enter Fullscreen mode. From here I could not escape the Fullscreen mode, Alt-F4 didn't work, Escape didn't work and no Ctrl-# combination nor Alt-# combination did anything.

I had to either Alt-Tab and close the program via Right-clicking it on the Taskbar or by using Task Manager and this was the only way to exit Fullscreen as well, since the emulator would launch in a Windowed state when I re-opened it.

After resetting the Hotkeys as per a suggestion in this bug report: F11 allowed me to exit Fullscreen and  Escape (no confirmation prompt?), Ctrl-Q and other hotkeys worked without issue but Alt-F4 remains suppressed.

**Comment by RhinoKneel** [comment]
As noted in my issue regarding controller inputs (#163), make sure if you're using XInput that nothing is set to Axis2- or Axis5-. These appear to be rapidly inputting once the game has loaded, and resulted in keyboard inputs failing to work after. As I had mine set to my shoulder buttons, I didn't realize it until playing GBA games that it was doing that.

**Comment by ZachBacon** [comment]
Hmm, I'm honestly wondering if the input code needs to be rewritten or attempt to fix it. I'll have to see what I can do about it, especially with the current bios issue people have been reporting. I can't make promises due to the fact my full-time job takes priority, but I'll try what I can.

**Comment by Steelskin** [comment]
I am going to disable binding to multiple accelerators as part of the input refactor tracker in #745.
Accelerators were the next part of my refactor anyway.
