### ISSUE TITLE
Can't background input in VBA-M 2.0.2

### ISSUE THREAD

**Issue by h3x4n1um** [visualboyadvance-m/visualboyadvance-m#207]
I'm using VBA-M 2.0.2 to play TLoZ: Four Swords Adventures with my friend but VBA-M doesn't accept the background input although I unchecked **Pause when inactive**

**Comment by retro-wertz** [comment]
been testing four swords network and works fine on linux...
in anycase, incomplete details. please add more info or better yet, update using issue template.

**Comment by Squall-Leonhart** [comment]
Expected behaviour
Background Input and toggle functionality

Actual behaviour
Neither exist on Windows

### Steps to reproduce the behaviour
Start game
Click off the window
Press buttons

ROM details
Not applicable

### Option details

Video driver opengl

Sound driver xaudio

### Build details

Windows, 2.1.0-2a79648

Version of code (pre-built binary version, or commit ref, or just "master"):
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-457876139

### Hardware details:
Keyboard

**Comment by Alegria4486** [comment]
Hi, I'm using the VBA-M 2.1.0 version and I see that untoggle "pause when inactive" doesn't do anything: weather it is toggled or not, when the game is on background, the bgm and the screen animations work, and the inputs are impossible. Also, the "Pause" on Emulation menu doesn't work.

### Please fill out this form:

### Expected behavior:
[https://cdn.discordapp.com/attachments/340141739543363586/572517340579627044/unknown.png](url)
-the Pause button should pause the game
-when "pause when inactive" is toggled, the game should be paused when on background window on the computer, including for the sounds and the animations on-screen. Plus it would be impossible to play as long as the game is on background
-when "pause when inactive" is untoggled, when the VBA-M window is in background, the game should have its music and animations played. Plus it would be possible to use the inputs, so to play the game like if it was on foreground.

### Actual behavior
-"Pause" doesn't do anything
-"pause when inactive" doesn't freeze the game. You can't use the buttons, so you can't play, but the game still plays its music and animations.
-untoggle "pause when inactive" doesn't make the inputs available when in background. The result is the same as when that option is toggled

### Steps to reproduce the behavior
-open a game
-click several times on emulation>pause and not noticing any change
-click outside the window and remark the "pause when inactive" doesn't work as planned
-untoggle "pause when inactive", click outside the window, use the configured inputs and see it doesn't work.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
-pokemon Trading card games 2 - GR Dan Sanjou! - fan translation (gbc)
-pokemon mystery dungeon red rescue team (gba)
-wario land - super mario land 3 (world) (gb)
-wario land 3 (gbc)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
-Tetris DX (gb) does everything I said, except it takes every input on background, weather "pause when inactive" is toggled or not 

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by retro-wertz** [comment]
@Alegria4486 
im using this to test (despite it being older) https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-479988998
and i cant replicate any of the conditions you stated.
- clicking on Emulation > pause - pauses every game just fine
- when pause when inactive is enabled (checked), every game freezes when vbam window is not active.

i did find a bug though with using a different method. and that is if Pause is enabled, and Pause when inactive is also enabled, when vbam window is inactive it pauses game as expected. But clicking on vbam window (hence making it active) will unpause the game when it should not since Emulation>Pause is still activated @rkitover

**Comment by Alegria4486** [comment]
Hum... I discovered this when I tried to have an infrared pop card! connection between two pokemon tcg2 saves, at first I thought it was a connection problem, then I realized I had to click the A button on each window at the same time and it wasn't working. Of course each window has its own set of inputs. I don't see what could be different, what parameters could change it... 

 I tried it several days, and I turn my computer off every night. Now I'll try to uninstall and install again vbam, but this means I'll have to configure everything again and I'm laaaaazy. Uh, well...

**Comment by rkitover** [comment]
This definitely doesn't work now, I would have to create some kind of global hotkey functionality that could be toggled, because otherwise it's completely normal that an unfocused application does not get any input.

**Comment by Alegria4486** [comment]
just to make sure you read this, I tried several roms and Tetris DX was the only one that could work with the inputs on background. except it worked too when "pause when inactive" was on.

**Comment by andresdb91** [comment]
Background input on Windows 10 works fine until SVN r1490, but I couldn't make it work on any newer version. I don't know if it's of any help but I'll link it below.

Link to old Sourceforge page (r1490): https://sourceforge.net/p/vbam/code/1490/

**Comment by ZachBacon** [comment]
@andresdb91 try a nightly if you haven't already. https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-522354350

**Comment by rkitover** [comment]
Just to be clear, are you guys talking about background keyboard or joystick input? And which would be more important to you?

The SVN version is likely the MFC version, a completely different codebase.

**Comment by h3x4n1um** [comment]
> 
> 
> Just to be clear, are you guys talking about background keyboard or joystick input? And which would be more important to you?
> 
> The SVN version is likely the MFC version, a completely different codebase.

I have problem with the keyboard background input, haven't try controller yet :p

**Comment by tdeeb** [comment]
I'm having this same issue with controllers on Linux on version 2.1.4-8e883631 (commit https://github.com/visualboyadvance-m/visualboyadvance-m/commit/8e88363163283dd64f4f2c3e7fc93d0c185fb6b2) built from source. **Emulation > Pause when inactive** is not checked.

Other emulators such as mGBA allow input when the window isn't focused. This is a dealbreaker for link-cable games since only one window can be focused at a time.

**Comment by rkitover** [comment]
@tdeeb thanks for the report, this may have worked before but we just did some work on input handling and I will make sure it works and report here.

**Comment by v1993** [comment]
Can confirm this on KUbuntu. Unfocusing VBA-M window prevents it from receiving even joystick input. Interestingly, windows version running in wine seems to ignore all joystick input at all (I can bind buttons fine, keyboard works for input).

**Comment by denisfa** [comment]
@v1993 What version of vbam are you using? I am having the opposite issue of yours, my joystick input is detected even if the screen is not focused, which is how I am running linking tests. If you can, please attach your `vbam.ini` so we can take a look.

**Comment by v1993** [comment]
@denisfa I'm using a recent version built from commit 81c88227fabe4d7703ba9679d6789506b5f554ee. [`vbam.ini`](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4932156/vbam.txt) attached.

**Comment by mstan** [comment]
Hi @rkitover .

When attempting to use VisualBoyAdvance-M 2.1.4, I am able to reproduce this on Windows 10 using keyboard input.

I have four instances of VBA-M running. Each with unique input keys per instance. With "Pause while Inactive" not checked.

Expected behavior that each VBA-M will accept it's unique keys while it is not in focus. 
Current VBA-M must be in focus to accept its key inputs.

It doesn't seem to matter if one of the four VBA-M are in focus, or if none of the four are in focus.

**Comment by ZachBacon** [comment]
@mstan question, what platform? Windows Linux or macos? If windows can you run a nightly from https://win.vba-m.com/nightly/ and report back? And if on Linux, assuming you have snap support, can you install vba-m edge package? Both are built from latest sources.

**Comment by mstan** [comment]
@ZachBacon , Windows 10. Just downloaded and tested a nightly. Looks like it works!

**Comment by muizzsiddique** [comment]
I can still reproduce this problem and have another related issue.

The emulator doesn't take background input from the keyboard on the latest stable version (2.1.4 from the Releases tab here) and latest nightly (following the link provided by ZachBacon). **Expected behaviour:** Disable Pause When Inactive Window, click off the Window (either on the Desktop, Taskbar, etc.) and press the configured keys, then see the game listening to the input.

Also, disabling Pause When Inactive Window doesn't work when I click on any of the buttons on the menu bar, the game still pauses. **Expected behaviour:** Click on File, Emulator or any other menu item. The game continues to run.

I'm running on Windows 10 2004 64-bit.

**Comment by rkitover** [comment]
@muizzsiddique 

The issue with pausing when you use menus in Windows we can do nothing about right now, this is a complicated technical issue related to the Windows event loop, and our own event loop.

As far as background input goes, that should mostly work, since denisfa did this shortly before he left, in the nightly. Are you using the keyboard or a controller?

**Comment by MarbleQ22** [comment]
> @muizzsiddique
> 
> The issue with pausing when you use menus in Windows we can do nothing about right now, this is a complicated technical issue related to the Windows event loop, and our own event loop.
> 
> As far as background input goes, that should mostly work, since denisfa did this shortly before he left, in the nightly. Are you using the keyboard or a controller?

I apologize for disturbing but I cant access the nightly site, and I'm also having the same no input being accepted in the background. Is there anywhere where I can download nightly releases, like the one that fixed the input issue? Thanks in (gameboy)advance!

**Comment by muizzsiddique** [comment]
> 
> 
> @muizzsiddique
> 
> The issue with pausing when you use menus in Windows we can do nothing about right now, this is a complicated technical issue related to the Windows event loop, and our own event loop.
> 
> As far as background input goes, that should mostly work, since denisfa did this shortly before he left, in the nightly. Are you using the keyboard or a controller?

I am very sorry for a late response. I was using a controller. Typically, I can send Xbox Cont. input to other emulators while I'm focusing on other Windows.

**Comment by MarbleQ22** [comment]
Dunno how active this thread is, but I opened up a new issue about this, since the link for nightly is completely dead and can't be accessed

**Comment by Squall-Leonhart** [comment]
Stale
