### ISSUE TITLE
Feature Request: Flatpak installation of VBA-M.

### ISSUE THREAD

**Issue by soundconjurer** [visualboyadvance-m/visualboyadvance-m#235]
Make flatpak builds on flathub.org. This will allow for an easily accessible more up to date version for users.``

**Comment by ZachBacon** [comment]
I'd be more apt to support snaps over flatpak

**Comment by soundconjurer** [comment]
Why snaps over flatpak? I've used both, I definitely prefer the flatpak.

**Comment by soundconjurer** [comment]
From an end user point of view, it really doesn't matter much to me. Whichever can be pulled off better should be fine, but I've not had the snap framework function on any other distro without some tweaking other than Ubuntu. Fortunately for, that's my main distro.

**Comment by ZachBacon** [comment]
I primarily develop on solus, which has snap integration and confinement.

**Comment by nilsoffermann** [comment]
Today I attempted to package VBA-M as a Flatpak myself because I'd like to see it packaged as one. Personally I prefer Flatpaks over Snaps and using it as a native package often times isn't the best solution either (lots of distros, outdated repos etc). In the attachment you can find my Flatpak manifest that seems to be working fine so far. Controller input, sound etc seems so be working. But I've only tested it for a few minutes so far so there might be stuff I missed, since this is also my first attempt at packaging a Flatpak.
To build the Flatpak simply navigate to the directory with the .yaml file and run (assuming Flatpak build tools are installed)
`mkdir build-dir && flatpak-builder build-dir com.vba-m.VisualBoyAdvance-M.yml --user --install`
[com.vba-m.VisualBoyAdvance-M.yml.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/5336400/com.vba-m.VisualBoyAdvance-M.yml.txt)

**Comment by rkitover** [comment]
@nilsoffermann Thank you very much for this, I will get a flatpak published ASAP.

**Comment by nilsoffermann** [comment]
I fixed the way I went about renaming the .desktop (and appdata) file which I didn't know flatpak-builder had a built-in function for, which the manifest it now using instead of manually renaming them. Sorry for the inconvenience, I was just figuring stuff out myself
[com.vba-m.VisualBoyAdvance-M.yml.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/5408066/com.vba-m.VisualBoyAdvance-M.yml.txt)

**Comment by Gameskiller01** [comment]
@rkitover Did you ever get the flatpak published? I can't seem to find it, but I'd very much like to have it as a flatpak as well.

**Comment by ZachBacon** [comment]
Flatpak isn't quite on the radar at the moment, but it is a planned thing to do.

**Comment by rkitover** [comment]
Yeah, as Zach said, our priority right now is to do another release, we haven't done one in like 3 years. The flatpak stable branch would be based on the release anyway, so we have to do that first. The snap which Zach maintains will get updated then as well.

**Comment by Gameskiller01** [comment]
Fair enough, I look forward to it then. The version I compiled from source works perfectly fine for now anyway.

**Comment by matthewpetch** [comment]
bump

flatpak (or an appimage) would be incredibly helpful for steam deck owners

**Comment by ZachBacon** [comment]
Don't bump. It's in the plans. Just I don't have a lot of time anymore.
