### ISSUE TITLE
Disabling translation

### ISSUE THREAD

**Issue by magiblot** [visualboyadvance-m/visualboyadvance-m#288]
Hi there,

I'm using the `vbam-wx` package in Arch Linux.

My locale settings are set to Spanish and so VBA-M's interface uses the Spanish translation. However, I am very disappointed by this translation. Not only it looks google-translated (since there are out-of-context words that just match the literal translation of what I guess were the original words in English), but it also makes it really difficult to understand what certain functions of the program do.

I was expecting to find an option to change the translation in use in `Settings > General` or in `~/.vbam/vbam.conf`, but I found none.

Is there any way to change it?

Lots of thanks.

**Comment by ZachBacon** [comment]
This is done at compile time. You'd have to add to the compile string -DENABLE_NLS=OFF On the other hand if you want to contribute translations. We have a transifex project dedicated for translations.

**Comment by magiblot** [comment]
I'll take it into consideration. Thanks.

**Comment by ZachBacon** [comment]
At some point though, I'll see about resyncing the translations. Some of them have been updated

**Comment by magiblot** [comment]
Well, I figured out I can change the translation like this:

`env LANG=en_US.UTF-8 visualboyadvance-m`

**Comment by ZachBacon** [comment]
@cyberdyne-sys your language request has been accepted, but know this, I work 11 hours in a warehouse, moving furniture, all of my time and energy is spent so I CAN SURVIVE. If you have a problem with that, I'm sorry, this is a complete volunteer effort. I volunteer my time to make something and all you do is complain.
So I rather you not complain and act all entitled because something isn't done in a timely manner.
