### ISSUE TITLE
Cant click on New game on Pokémon Glazed with the right key

### ISSUE THREAD

**Issue by okajofmarvel** [visualboyadvance-m/visualboyadvance-m#363]
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
Please fill in the details, what version of the emulator etc. We need this information to better diagnose your issue.

**Comment by retro-wertz** [comment]
Pokemon Glazed is a romhack of Pokemon Emerald. I dont know where you got your rom or how you are patching existing pokemon emerald, New Game should allow you to start a new game as expected.

Other than that, you have not filled up template nor updated with details since the last time it was requested.

Please create a new ticket if its still an issue. closing issue.

![screenshot_2019-02-19_09-06-07](https://user-images.githubusercontent.com/23315382/52983331-9e8d3780-3425-11e9-8476-bf5e826d385f.png)
