### ISSUE TITLE
Non-ASCII keys aren't saved as an input key

### ISSUE THREAD

**Issue by anewuser** [visualboyadvance-m/visualboyadvance-m#493]
### Expected behavior
Map `A` to <kbd>Ç</kbd> on my keyboard.

### Actual behavior
The input field is cleared after I close the Joypad Configuration window.

### Build details
Windows 10 
VBA-M 2.1.3

**Comment by rkitover** [comment]
use latest nightly, this is fixed

**Comment by anewuser** [comment]
@rkitover 

![screen](https://user-images.githubusercontent.com/6733770/63639530-ae9f0180-c66a-11e9-8b47-065db8a216ed.gif)

![version](https://user-images.githubusercontent.com/6733770/63639531-b2cb1f00-c66a-11e9-9fb2-e1c3e0e0db17.png)

**Comment by rkitover** [comment]
Ok apparently it's not fixed then, sorry. I will take a look.

**Comment by rkitover** [comment]
It does not even let me enter non-latin characters.

**Comment by rkitover** [comment]
This is going to be difficult because `wxAcceleratorEntry` does not support unicode keys.

**Comment by rkitover** [comment]
@denisfa 

I'm thinking I'll:

- replace all keyboard APIs to take `(mod, key, char)` instead of just `(mod, key)` with the char from `GetUnicodeChar()`
- make a subclass of `wxAcceleratorEntry` called `wxUnicodeAcceleratorEntry` that also stores the char
- rewrite `FromString` to handle modified unicode chars not parsed by `wxAcceleratorEntry`
- change all the code to use the new APIs and class, and the config to store the char
- make global `OnKeyDown`/`OnKeyUp` events to process the new format of the accelerators instead of letting wx do it (so that we support this for UI accelerators too, not just game keys.)

thoughts?

**Comment by rkitover** [comment]
@denisfa fixed this in baa0341b and 91a6b53e with a minor followup by me in 306f92f5.
