### ISSUE TITLE
SIGSEGV with patches in GBA mode (which make rom bigger)

### ISSUE THREAD

**Issue by ArtiiP** [visualboyadvance-m/visualboyadvance-m#549]
my working tree based on current 

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004ef561 in CPUInit (biosFileName=<optimized out>,
    useBiosFile=useBiosFile@entry=false)
    at D:/msys64/home/___/vbam/visualboyadvance-m/src/gba/GBA.cpp:3313
3313            *((uint16_t*)&rom[0x1fe209c]) = 0xdffa; // SWI 0xFA
```

in patchApplyUPS (and WIP patchApplyBPS) 
we have 
```
    if (dataSize > *size) {
        *rom = (uint8_t*)realloc(*rom, dataSize);
```
any patch that make gba rom bigger make this sigsegv,
why?
let's see 
gba use
```
int CPULoadRom(const char* szFile)
{
    romSize = SIZE_ROM; 
```
SIZE_ROM = 32MB

but gb use utilGetSize() => rom size is dynamic, 

and that means we must realoc for gb and not for gba 
ouch

or fix GBA.cpp

**Comment by denisfa** [comment]
@ArtiiP This is actually awesome. Not so long ago, we were examining a mysterious ROM padding done on `panel.cpp`. There was no obvious explanation (or seemingly self explanatory comment), and it was only brought to attention due to an UPS patch for a pokemon game (FireRed, if that matters) not being applied due to the padding. I believe that comment on the core about the issues regarding this now makes sense.

> or fix GBA.cpp

No doubt about it! Could you give more info about your test? What game and what patch did you try to apply? (do not post links directly, otherwise you account may get flagged)

**Comment by ArtiiP** [comment]
i  trace the code by eyes :)

libretro use CPULoadRomData
but sdl i wx use CPULoadRom

only in CPULoadRomData romSize is overwriten to current rom size 
`romSize = size % 2 == 0 ? size : size + 1;`
i don't see this in CPULoadRom

in CPUInit romSize is checked before write 
`if (romSize < 0x1fe2000)`
good

**Comment by ArtiiP** [comment]
ach, sorry.
rom name: Magical Vacation (J) 
patch: Eng1.0 magicalpatcher (in bps format)

you can use https://github.com/ArtiiP/visualboyadvance-m/tree/bps to work this :)

one more thing, i use MS EMET (Enhanced Mitigation Experience Toolkit) on this machine. 
That may by the reason, why realloc and access beyond boundary kick sigsegv

**Comment by negativeExponent** [comment]
just Quick reply here:
* rom pointer should not be resize/reallocated. this is initially allocated to use entire 32MB of cart space. The unused space if filled with out-of-bounds return values.
* if size is changed after patching, romSize, should be updated as well which is currently not directly accessible and is not currently implemented.
so disabling this line:
```
if (dataSize > *size) {
            // SIGSEGV in /src/gba/GBA.cpp:3313 [*((uint16_t*)&rom[0x1fe209c]) = 0xdffa; // SWI 0xFA]
            //*rom = (uint8_t*)realloc(*rom, dataSize);
        } 
```
and updating romSize like so(quick and dirty way):
```
            applyPatch(pfn.GetFullPath().mb_str(), &rom, &size);
            // that means we no longer really know rom_size either <sigh>
			romSize = size;
```

should make things work (as far as loading the rom)
![Screenshot_2019-10-21_10-32-09](https://user-images.githubusercontent.com/54053706/67172494-26c93f80-f3ee-11e9-8630-15a665d3a935.png)

in the long run, vba-m should allow loading rom into buffer and patching if necessary before sending the final rom into CPULoadRom();

**Comment by mudlord** [comment]
Yeah, this should be looked at, as well as other things in the core. I was meaning at some point in the past to go through the GBA and GB cores with a fine toothed comb to clean up some things as well as work on core accuracy. I guess this was one of those things.

**Comment by ArtiiP** [comment]
@negativeExponent  GB don't use 32MB for *rom  (gb use utilGetSize)

that means we must resize/realloc if patched rom is bigger.

**Comment by SatoMew** [comment]
> you can use https://github.com/ArtiiP/visualboyadvance-m/tree/bps to work this :)

Many thanks for this! 😄 Are there any plans to get this into the official VBA-M anytime soon?

> one more thing, i use MS EMET (Enhanced Mitigation Experience Toolkit) on this machine.

You should uninstall EMET because Microsoft [retired it long ago](https://support.microsoft.com/help/2458544) in favor of improving and including its functionality in Windows 10. There are alternatives like OSArmor if you're using an older Windows version.

**Comment by ZachBacon** [comment]
@SatoMew I'll probably look into adding it at some point
