### ISSUE TITLE
filters xbrz 4x and above are slow with the simple video driver

### ISSUE THREAD

**Issue by ZachBacon** [visualboyadvance-m/visualboyadvance-m#55]
### Expected behavior
xbrz filters 4x and above work as described.
### Actual behavior
xbrz filters 4x and above only seem to work with opengl, but for the simple video driver stutters.
### Steps to reproduce the behavior
Use the simple driver and select the filter.
### Build details

Operating System (Windows, Mac, Linux, etc.): All Platforms

Interface (wx and SDL, default is wx): wxWidgets

Version of code (pre-built binary version, or commit ref, or just "master"): current master

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:
Video issue

**Comment by Squall-Leonhart** [comment]
these filters were intended for the multithreaded D3D renderer, they are cpu intensive and will perform badly on the simple renderer

we need to get on top of mudlords suggestion and implement a multithreaded tile renderer.

**Comment by rkitover** [comment]
Looking at this again.

The only platform where the simple driver is slow is Mac, because of quartz. The filter may make it even slower because it upscales the image.

There is some kind of filter thread code in the wx code, I need to see if it actually still works, this would be in effect before the output driver such as simple or opengl.
