### ISSUE TITLE
Bomber Man GB 3 (GameBoy) characters, enemies and menu pointers not visible

### ISSUE THREAD

**Issue by Hexfire7th** [visualboyadvance-m/visualboyadvance-m#572]
### Expected behavior
Interactive elements should be visible 

### Actual behavior
They aren't. Layer issue perhaps?

### Steps to reproduce the behavior
Simply open up the rom and get to the playable part. 

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Bomber Man GB 3 (Japan) (SGB Enhanced).gb

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
So I'm gonna close #571 because you posted this twice. Also please follow the template. We need versions you used etc. 

These are ALL important information. If you can add those details that would be great.

**Comment by denisfa** [comment]
@Hexfire7th As a workaround using version `2.1.4`: go to `options` > `Game Boy` > `Configure ...`. Check if `Emulated system` is NOT set to `Game Boy Color` or `Game Boy Advance`. It should work with others.

@ZachBacon I can confirm this on latest version on Linux, but only when using emulated system like above. Not sure if this is an actual bug, though.

**Comment by denisfa** [comment]
@Hexfire7th Sorry about the delay here, but I could only check now that this is not an actual bug. If you check your configuration, you will very likely see that you are forcing the emulator to open this rom on either Game Boy Color or Game Boy Advance. This is not supported because of some technical details that I won't explain now.

If you would like to play with colors, use the Super Game Boy. Now, if you did this because there is some other game that takes advantage of using a specific game boy (like Zelda - Oracle of Ages/Seasons) and kept like this for all other games, could you please provide more information about your setup? I like the idea of a game profile, that could handle things like this.
