### ISSUE TITLE
Stuck at High Speedup

### ISSUE THREAD

**Issue by LilBeanBoi** [visualboyadvance-m/visualboyadvance-m#627]
Sorry this is not any technical stuff, but vba seems to be stuck at 200-250% speed and I can't seem to fix it. Any help?

**Comment by denisfa** [comment]
@LilBeanBoi We have had a couple of issues of the speed being stuck at high values. I will assume you have the latest stable version `2.1.4`... Also, Windows or Linux?

Has it been like this since you very first try playing a game? Or did it start happening after you tried to do some configuration?

Could you try: `help`--> `factory reset` (backup your configuration first). If it works, could you send the `vbam.ini` that did not work?

**Comment by LilBeanBoi** [comment]
@denisfa I have the 2.1.3 version on Windows 10, and this issue started randomly, but I don't think changing video filters might have affected that. I tried to do a factory reset and it worked! Unfortunately I don't know what vbam.ini is but the issue is fixed, thank you

**Comment by rkitover** [comment]
Glad things are working for you now.

If you have any problems feel free to open an issue and we'll help the best we can.
