### ISSUE TITLE
Pokemon Box can link to Ruby/Sapphire USA roms only

### ISSUE THREAD

**Issue by Real96** [visualboyadvance-m/visualboyadvance-m#642]
I'm using last dolphin commit + last vba-m commit. To reproduce the error, you just have start a connection from JPN/EUR Pokemon Box to JPN/EUR Pokemon Ruby/Sapphire (same results with BIOS or without).
I'm able to connect Dolphin to VBA-M using Pokemon Box USA version with Ruby/Sapphire USA version. But it doesn't work with both JPN/EUR versions of Ruby/Sapphire. I tryed to use BIOS in dolphin and VBA-M, but problem is always the same.
These are the 2 screens in which i stuck (can't pass this screen, no freezes or errors):
![Eur Box error](https://user-images.githubusercontent.com/20956021/78459849-61811480-76bc-11ea-8def-ac32981e787b.png)

![Jpn Box error](https://user-images.githubusercontent.com/20956021/78459850-634ad800-76bc-11ea-82d3-ad8fb48fd8ca.png)

This is instead the screen of the correct link with an USA rom:
![Usa Box error](https://user-images.githubusercontent.com/20956021/78460166-dd7c5c00-76be-11ea-853f-cf52803b9362.png)

**Comment by ZachBacon** [comment]
Please use the template. We need to know information such as the version of visualboyadvance-m you are using etc.

**Comment by Real96** [comment]
> Please use the template. We need to know information such as the version of visualboyadvance-m you are using etc.

Sorry, if needed i can edit it. Anyway, i used version M 2.1.4-b21880ea. There is also dolphin version in the screens

**Comment by Liger0** [comment]
To me, it doesn't link using USA roms either.
Only the VisualBoyAdvance-M-WX v2.0.0.0 (as reported by windows version at least, because it's not specified on the emulator and I noticed some vba-m versions report different versions on windows and in the "about" dialog) connects. 
Vba-m 2.1.4 only displays a black screen on the VBA and nothing happens on Dolphin.

**Comment by Liger0** [comment]
So far, to me even the USA rom doesn't work on vba 2.1.4 x64 as the screen remains black after the intro, when the box screen is supposed to appear.
I am sure it worked in the past, not sure why it doesn't anymore. I even tried removing the settings from appdata and using new empty local ones using the bios, RTC, directories, etc, but no luck.
It works on vba-m-wx 2.0.0 beta2 x32.
I can't test vba 2.1.4 x32 to see if the x64 is the issue because when entering the link settings, vba 2.1.4 x32 plainly crashes.

**Comment by rkitover** [comment]
Please do any testing with a recent nightly, 2.1.4 is already almost a year old.

**Comment by JMC47** [comment]
This is a Dolphin bug.  See -> https://github.com/dolphin-emu/dolphin/pull/9625

Will be fixed later today and this is unrelated to VBA-M so this can be closed.

**Comment by Real96** [comment]
Tested with last vba-m commit and it works great! Closing this
