### ISSUE TITLE
Error with sign extended multiplication

### ISSUE THREAD

**Issue by DenSinH** [visualboyadvance-m/visualboyadvance-m#701]
I wrote a [fuzzer](https://github.com/DenSinH/FuzzARM) for the GBA, and among testing it on my own emulator, some others and on hardware, I also tested it on VisualBoy Advance. It turns out there is a mistake in sign extending long multiplication (`SMULL/SMLAL`). I posted a screenshot of your emulator failing the ROM in the repo to showcase the eWRAM error info dump (I hope this is okay, your memory viewer is very nice and useful). Below is a screenshot, including the expected/actual behavior. A way to reproduce it is to simply run the ROM in my repo (or generate your own with the script haha). 

![VBA smull error](https://user-images.githubusercontent.com/25347040/87579784-c47c4180-c6d6-11ea-9f09-8eb10ffbe98e.png)

The test that it fails is basically `SMULL r4, r3, r0, r1` (forgive me if I have the order of the destination registers wrong, `r3` should be the `RdHi` register).

I did not check if VBA fails more instructions (the generated ROMs test all arithmetic/multiply/most load store instructions in both ARM and THUMB mode, so you could check if it fails more.

I hope this helps!

### ROM details

The ROM details are as described above, and are also described in the README of my [repo](https://github.com/DenSinH/FuzzARM).

### Build details
I tested this on windows, and I think it was on the most recent build, I'm not completely sure about that though. It shouldn't really be platform dependent anyway.

**Comment by denisfa** [comment]
@DenSinH Thanks for this report. Were you using the latest nightly for this testing? It is available [here](https://win.vba-m.com/nightly/). I did a quick testing using the ROM available on the root of your repo (`main.gba`), and no errors appeared. Do you still have the ROM that causes this? If so, could you attach here, please?

>  (I hope this is okay, your memory viewer is very nice and useful). Below is a screenshot, including the expected/actual behavior. A way to reproduce it is to simply run the ROM in my repo (or generate your own with the script haha).

There are no issues for you doing this. It is just weird because our memory viewer does not work at all. I believe you are using a really old version, at least according to your screenshot (`2.0.1`). Also, keep in mind that this project is lagging behind others in terms of accuracy and other metrics. So you should always check with other emus and official docs for test creation and their results.

We will catch up one day, though.

**Comment by DenSinH** [comment]
@denisfa I can't test it myself right now unfortunately, but the ROM that caused the problem is the ROM in the repo iirc, if it doesn't display a message like in the screenshot it is probably fixed in a different version.

I must have gotten my build of VBA from elsewhere or something, because I downloaded it pretty recently (about 1-2 months I think). 

If it was a different ROM that caused it, it wouldn't matter much, cause it is highly unlikely that any ROM I generate does not contain a `SMULL/SMLAL` test case that would go wrong on that version of VBA.

If it is fixed already, sorry for the invalid issue!

**Comment by rkitover** [comment]
@DenSinH thank you for the report anyway, and if you get more information on this please update us here.
