### ISSUE TITLE
Screen goes wacky when streaming a game on Discord

### ISSUE THREAD

**Issue by Aescula** [visualboyadvance-m/visualboyadvance-m#767]
### Expected behavior
Stream goes through on Discord, I can play while sharing it with my friend.
### Actual behavior
As soon as I hit the Share Screen button on Discord and select VisualBoy (v M 2.1.4-4aab08c4) the screen starts flipping between right-side-up and upside down every frame, no animation of the actual game.
### Steps to reproduce the behavior
Try streaming to a friend on Discord.

**Comment by rkitover** [comment]
Try changing display driver to simple from opengl.

**Comment by Aescula** [comment]
Using the Simple driver works. The OpenGL is screwy. This works as a fix, but the bug should still be noted.

**Comment by rkitover** [comment]
I agree that we should fix this behavior if possible.

**Comment by Squall-Leonhart** [comment]
Based on eduke32's method, this has been fixed in https://github.com/visualboyadvance-m/visualboyadvance-m/compare/discord-fix and will be merged to master after some testing.

Try this
[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11964207/visualboyadvance-m.zip)
