### ISSUE TITLE
Unable to Pause

### ISSUE THREAD

**Issue by DrWacker** [visualboyadvance-m/visualboyadvance-m#788]
### Expected behavior
When you select Emulation->Pause the game will pause

### Actual behavior
Select Emulation->Pause the game keeps playing though the menu indicated that pause is selected

### Steps to reproduce the behavior
Run a game
Select Emulation-> Pause
try to move/select/play game and the game isn't paused

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Emerald (GBA)
Pokemon Crystal_Clear (GB)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
N/A

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/6318906/101206549-87d0c880-362c-11eb-97f7-1b6c61616f7a.png)
![image](https://user-images.githubusercontent.com/6318906/101206619-9d45f280-362c-11eb-9e75-95eafb80600d.png)

If you are using a BIOS file, please say which one.
default

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows
Version of code (pre-built binary version, or commit ref, or just "master"):
tested on
4aab08c4
7aa0509e

**Comment by Squall-Leonhart** [comment]
Not seeing this as the reporter has stated, but the pause item is not allowing emulation to be unpaused in my case, i have to ctrl+p to resume.

**Comment by Jamiras** [comment]
Still seeing this behavior on a5b2d070. (Windows, self-built)

* Emulation>Pause always pauses, regardless of the current pause state.
* Ctrl+P always unpauses, regardless of the current pause state.

* Emulation>Next Frame pauses and advances a frame (always works).
* Ctrl+N always unpauses, regardless of the current pause state (never works).

Changing Pause when Inactive has no effect on the above behavior.

**Comment by Jamiras** [comment]
The keyboard shortcuts are failing because `SetMenusOpened` gets called with `true` before calling `OnPause` or `OnNextFrame`, and with `false` afterwards. When it changes from `true` to `false`, `paused` and `pause_next` are set to false.

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/a5b2d070dc79057e848a97ec92a93e874ca0f3fc/src/wx/wxvbam.cpp#L1143-L1158

Similarly, when using the menu, `SetMenusOpened` sets them both to false before calling `OnPause` or `OnNextFrame`, so they're forcibly re-enabled.

**Comment by Squall-Leonhart** [comment]
Fixing this can be done a few ways.

1. We rip out the Ifdef's and fix Dsound so it times out on buffer exhaustion (so it doesn't loop the last sound)
2. We Rip out the ifdefs, and remove Dsound entirely.
3. Rip out the Ifdefs and move Emulation and Rendering off main thread so that all ports have the same behavior.
