### ISSUE TITLE
[Bug]: Joypad not available for vba-m snap

### ISSUE THREAD

**Issue by erishiamu** [visualboyadvance-m/visualboyadvance-m#934]
### Expected behavior?

Inputs from a usb-attached gamepad can be configured in the input menu

### Actual behavior?

The program does not acknowledge inputs from attached usb joypad. Joypad input works in jstest. Some searching has yielded 'sudo snap connect snapname:joystick' as a solution for other projects, however joystick/raw-usb plugins are not in this snap. 

### Steps to reproduce the problem

0. try to build from source, fail. :)
1. Install vba-m snap with sudo snap install visualboyadvance-m --beta (behavior occurs with edge as well)
2. Launch visualboyadvance 
3. options > input > configure, select a button input and press corresponding joypad button

### Error messages?

N/A this does not crash, it simply does not work as expected. 

### What game were you playing

N/A this is duplicable without a rom loaded. 

### What settings are you using?

Video driver (simple, opengl):simple
Sound driver (directsound, xaudio, openal, SDL): sdl
Scale Filter Used?: apologies, I do not know what this means. 

### Specifications and Build details

VBA-M: 2.14-4-94b4a798, this was installed with snap not sure if its x86 or amd64
OS: (include version and OS build number using WinVer if on Windows): Kubuntu 21.10 
If using Linux, specify if using xorg or Wayland: xorg
CPU: Ryzen 5800x
GPU: radeon 5700 xt
RAM: 32gb Gskill DDR4 3200mhz

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Manic137** [comment]
Not sure if this works for you, but opening VBA as Administrator fixed it for me!

**Comment by Hooloovoo** [comment]
It looks to me as though this just needs `joystick` added to the list of plugs.

If I download the latest beta snap and install it manually:
```
snap download visualboyadvance-m --beta
snap install visualboyadvance-m_2.snap --dangerous
```
Nothing happens when I go into Input and try to configure the controls with joystick presses.

If I remove it and install it again in devmode:
```
snap remove visualboyadvance-m
snap install visualboyadvance-m_2.snap --devmode
```
It works as expected, reacting to gamepad presses on my wireless Logitech Rumblepad 2.

Using snappy-debug to capture a log while doing this:
```
sudo snappy-debug > snappy-debug.log
```
gives [this log](https://paste.ubuntu.com/p/6x6CxHMSwP/) including:
```
= AppArmor =
Time: Jul 31 22:05:46
Log: apparmor="ALLOWED" operation="open" profile="snap.visualboyadvance-m.visualboyadvance-m" name="/dev/input/event21" pid=46896 comm="visualboyadvanc" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
File: /dev/input/event21 (read)
Suggestions:
* add one of 'device-buttons, joystick' to 'plugs'
* add 'raw-input' to 'plugs'
```
Removing the snap again and unsquashing the snap with:
```
unsquashfs visualboyadvance-m_2.snap
```
lets me go into the squashfs-root/meta/ folder and edit the snap.yaml
Changing the:
```
apps:
  visualboyadvance-m:
    command: usr/bin/visualboyadvance-m
    command-chain:
    - snap/command-chain/snapcraft-runner
    - snap/command-chain/desktop-launch
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - x11
```
to add a 
```
    - joystick
```
underneath and then running a `snap try squashfs-root/` means that I can then run `visualboyadvance-m` and I have a version where the input configuration screen works as expected with the gamepad.

**Comment by ZachBacon** [comment]
So, I managed to build the updated snap, added the joystick, but it's still not usable. Mainly due to the fact it's not autoconnecting. You'd have to enable it manually for now. The only way to get it autoconnect is if I request it on the snapcraft forums, which I shall be doing so with in the next few days

**Comment by ZachBacon** [comment]
https://forum.snapcraft.io/t/autoconnect-for-visualboyadvance-m/37437 Request is in, just have to wait for approval.

**Comment by ZachBacon** [comment]
@Hooloovoo @erishiamu Apologies for the long delays. Request from the snapcraft team has been approved, Joystick is now set to autoconnect for vba-m's snap. I'll close this for now. Feel free to report anything though if you're still having troubles.

**Comment by Hooloovoo** [comment]
Works exactly as expected with stable snap, many thanks!
